# Generated by Django 5.0.6 on 2024-07-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_parent_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.banner'),
        ),
    ]
