# Generated by Django 5.0.6 on 2024-07-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_slug_product_slug_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
